name: cf-minip

services:
  qdrant:
    image: docker.m.daocloud.io/qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  redis:
    image: docker.m.daocloud.io/library/redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../../
      dockerfile: juxing-engine/backend/Dockerfile
    env_file:
      - ../backend/.env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=positions
      - EMBEDDING_MODEL_NAME=shibing624/text2vec-base-chinese
    volumes:
      - ./data:/data
    restart: unless-stopped
    ports:
      - "4100:8000"
    expose:
      - "8000"
    depends_on:
      - redis
      - qdrant


